export const APP_THEMES = {
  default: {
    name: "Default",
    primaryColor: "#707070",
    secondaryColor: "#e0e0e0",
    backgroundColor: "#f5f5f5",
    surfaceColor: "#ffffff",
    iconColor: "#707070",
    textColor: "#2d2d2d",
    textSecondaryColor: "#6f6f6f",
    borderColor: "#dcdcdc",
    hoverColor: "#d4d4d4",
    activeColor: "#5a5a5a",
    button: {
      background: "#707070",
      text: "#ffffff",
      hoverBackground: "#5f5f5f",
      disabledBackground: "#cfcfcf",
    },
    input: {
      background: "#ffffff",
      text: "#2d2d2d",
      border: "#ccc",
      placeholder: "#999",
      focusBorder: "#707070",
    },
    card: {
      background: "#ffffff",
      shadow: "0 1px 3px rgba(0,0,0,0.1)",
    },
    sidebar: {
      background: "#e8e8e8",
      text: "#2d2d2d",
      hover: "#dcdcdc",
    },
    success: "#4CAF50",
    warning: "#FFC107",
    error: "#F44336",
  },

  rufous: {
    name: "Rufous",
    primaryColor: "#a81c08",
    secondaryColor: "#f7d4cc",
    backgroundColor: "#fff8f7",
    surfaceColor: "#fff",
    iconColor: "#a81c08",
    textColor: "#2d2d2d",
    textSecondaryColor: "#6f6f6f",
    borderColor: "#e5e5e5",
    hoverColor: "#f3c2b9",
    activeColor: "#c01708",
    button: {
      background: "#a81c08",
      text: "#ffffff",
      hoverBackground: "#8f1907",
      disabledBackground: "#f4cccc",
    },
    input: {
      background: "#ffffff",
      text: "#2d2d2d",
      border: "#ccc",
      placeholder: "#999",
      focusBorder: "#a81c08",
    },
    card: {
      background: "#ffffff",
      shadow: "0 1px 3px rgba(0,0,0,0.1)",
    },
    sidebar: {
      background: "#fff0ed",
      text: "#2d2d2d",
      hover: "#f5e0dc",
    },
    success: "#4CAF50",
    warning: "#FFC107",
    error: "#F44336",
  },
};
